### ISSUE TITLE
[Mobile] Issues with Toolkit's DrawerFlyoutPresenter

### ISSUE THREAD

**Issue by jsinsel-kahua** [unoplatform/uno.toolkit.ui#869]
### Current behavior

These are issues on Android.  I never tested with iOS, but expected to work there as well.

1) First open of the flyout doesn't always render the content.  You can see the see-thru overlay is there.
Here's the first time
![image (1)](https://github.com/unoplatform/uno/assets/67480815/fe69330c-73b9-42d5-980d-a7762e3eaddb)

Subsequent opens work
![image (2)](https://github.com/unoplatform/uno/assets/67480815/f47ae372-59a4-4dbb-a39a-352cf6f7f2c3)

2) The slide-up animation doesn't work every time it's opened.  Seems to work every other time.

3) Trying to change the LightDismissOverlayBackground only changes what's below the content and not the rest of the dismiss area.
![image (3)](https://github.com/unoplatform/uno/assets/67480815/e9d31044-0466-4e76-bf28-c4f695a8da79)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
@jsinsel could you indicate which version of Uno you are using ?

**Comment by jsinsel** [comment]
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/67480815/151e42e4-f24b-48c0-b710-1658b6738701)

Let me know if you need more info.  Our sln has these setup for the heads.

**Comment by kazo0** [comment]
cc @Xiaoy312

**Comment by Xiaoy312** [comment]
@jsinsel-kahua Hi,
Could you provide a bit more on the setup for this flyout?
Things that I am particularly interested in are:
- attributes/properties used on \<Flyout\> in particular the FlyoutPresenterStyle and its definition if it is other than `(Left|Top|Right|Bottom)DrawerFlyoutPresenterStyle`
- mechanism used to open the flyout: Button.Flyout, Resources+Flyout.ShowAt, FlyoutBase.AttachedFlyout+FlyoutBase.ShowAttachedFlyout or other?

Ideally, if you can provide a repro sample that would be greatly appreciated. Since right now, I am having trouble reproducing this issue on my side with the same package version.

**Comment by Xiaoy312** [comment]
regarding point #\3:
> Trying to change the LightDismissOverlayBackground only changes what's below the content and not the rest of the dismiss area.

It seems to suggest that you are using a `Flyout` with a non-`Full` placement. Could that be the case here? If so, setting `Placement="Full"` should fix that part. Regardless the opening orientation, this placement should always be full.

**Comment by jsinsel-kahua** [comment]
@Xiaoy312 

I found that overriding the template to match what's here in github (instead of what one of our nventive consultants added) seems to show Blue.  But it does still have the initial show issues where the overlay is not what we desired or shows content.  Along with the extra margins.
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/67480815/648d487c-4c18-4691-ae03-341bc9c5f3b2)

**Comment by jsinsel-kahua** [comment]
@Xiaoy312 - example video


https://github.com/unoplatform/uno.toolkit.ui/assets/67480815/f1f3afeb-f22f-4c4d-804e-bb03cef6df8e

**Comment by Xiaoy312** [comment]
@jsinsel-kahua Could you provide a repro sample for this issue? We are unable to reproduce on our side the behaviors that you are seeing, making it difficult to isolate the cause.

**Comment by jsinsel-kahua** [comment]
@Xiaoy312 @jeromelaban So I spent some time with this today.  I pulled the drawer flyout code and XAML from here and put it into our shared project.  The drawer code seemed to work whether the content displayed or didn't.  I found that in the UserControl that doesn't display correctly, that if I hook the Loaded event and put a UpdateLayout call directly then it all works properly.  

@darenmay says there's an ongoing issue with loaded being fired too early.  Is it possibly related?

**Comment by Xiaoy312** [comment]
I am not sure if this is the case, but I suspect this issue could be related to the measure process.
Since we don't have a repro from your side, we will need your help to confirm this:
Can you add a hardcoded height to this element here:
![image](https://github.com/unoplatform/uno.toolkit.ui/assets/2359550/2978ca70-4485-454e-bb9b-0f37a606df99)
And, see if it shows up?
